post_install() {
    echo -e "\n** Following distros are supported."
    echo
    echo -e "** AcreetionOS"
    echo -e "** Arch Linux"
    echo -e "** ArchBang"
    echo -e "** Archcraft"
    echo -e "** Archman"
    echo -e "** Artix"
    echo -e "** BerserkOS"
    echo -e "** Biglinux"
    echo -e "** BlendOS"
    echo -e "** Bluestar Linux"
    echo -e "** CachyOS"
    echo -e "** Calam-Arch-Installer"
    echo -e "** Crystal Linux"
    echo -e "** EndeavourOS"
    echo -e "** Garuda"
    echo -e "** Helwan"
    echo -e "** Kiro"
    echo -e "** Liya"
    echo -e "** LinuxHub Prime"
    echo -e "** Mabox"
    echo -e "** Manjaro"
    echo -e "** Nyarch"
    echo -e "** Omarchy"
    echo -e "** ParchLinux"
    echo -e "** PrismLinux"
    echo -e "** RebornOS"
    echo -e "** StormOS"
    echo
    echo -e "**\n"
}

post_upgrade() {
    post_install
}



